import * as fs from 'fs';
import * as path from 'path';
import { AARRRMetrics, LeanViability } from '../parser/types';
import { calculateAllGaps, formatGap, isNegativeGap } from '../calculator/gap-calculator';
import { parseLeanViability } from '../parser';

export function generateAARRRMetricsHTML(metrics: AARRRMetrics, baseDir: string = process.cwd(), multiLayer: boolean = false): string {
  const metricsWithGaps = calculateAllGaps(metrics);

  // Load viability data if referenced
  let viability: LeanViability | null = null;
  if (metrics.lean_viability_ref) {
    try {
      const viabilityPath = path.isAbsolute(metrics.lean_viability_ref)
        ? metrics.lean_viability_ref
        : path.join(baseDir, metrics.lean_viability_ref);

      if (fs.existsSync(viabilityPath)) {
        viability = parseLeanViability(viabilityPath);
      }
    } catch (error) {
      // Ignore errors - viability is optional
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(metrics.title)} - AAARR Customer Factory</title>
  <style>
    ${getStyles(viability !== null)}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${escapeHtml(metrics.title)}</h1>
      <div class="meta">
        <span>Version: ${escapeHtml(metrics.version)}</span>
        <span>Last Updated: ${escapeHtml(metrics.last_updated)}</span>
      </div>
    </header>

    ${multiLayer ? renderPipelineOnly(metricsWithGaps, viability) : (viability ? renderTabbedView(metricsWithGaps, viability) : renderPipelineOnly(metricsWithGaps))}

    <footer>
      <p>Generated by BLUEPRINT - Business Layer Architecture</p>
    </footer>
  </div>

  ${viability ? `
  <script>
    function switchTab(tabName) {
      document.querySelectorAll('.tab-content').forEach(el => el.classList.remove('active'));
      document.querySelectorAll('.tab-button').forEach(el => el.classList.remove('active'));
      document.getElementById(tabName).classList.add('active');
      document.querySelector(\`[onclick="switchTab('\${tabName}')"]\`).classList.add('active');
    }

    function navigateToViability(anchor) {
      ${multiLayer ? `
      // In multi-layer mode, navigate to the main "Lean Viability" tab
      if (window.switchTab) {
        window.switchTab(null, 'Lean Viability');
        setTimeout(() => {
          const element = document.getElementById(anchor);
          if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'center' });
            element.classList.add('highlight');
            setTimeout(() => element.classList.remove('highlight'), 2000);
          }
        }, 100);
      }
      ` : `
      // In standalone mode, switch to viability tab within AAARR
      switchTab('viability-tab');
      setTimeout(() => {
        const element = document.getElementById(anchor);
        if (element) {
          element.scrollIntoView({ behavior: 'smooth', block: 'center' });
          element.classList.add('highlight');
          setTimeout(() => element.classList.remove('highlight'), 2000);
        }
      }, 100);
      `}
    }
  </script>
  ` : ''}
</body>
</html>`;
}

function renderTabbedView(metrics: AARRRMetrics, viability: LeanViability): string {
  return `
    <div class="tabs">
      <button class="tab-button active" onclick="switchTab('aaarr-tab')">AAARR Customer Factory</button>
      <button class="tab-button" onclick="switchTab('viability-tab')">Lean Viability Context</button>
    </div>

    <div id="aaarr-tab" class="tab-content active">
      <div class="customer-factory">
        ${renderPipeline(metrics, viability)}
      </div>
    </div>

    <div id="viability-tab" class="tab-content">
      ${renderViabilityContext(viability)}
    </div>
  `;
}

function renderPipelineOnly(metrics: AARRRMetrics, viability: LeanViability | null = null): string {
  return `
    <div class="customer-factory">
      ${renderPipeline(metrics, viability)}
    </div>
  `;
}

function renderPipeline(metrics: AARRRMetrics, viability: LeanViability | null): string {
  const stages = ['acquisition', 'activation', 'retention', 'referral', 'revenue'];
  const stageLabels: { [key: string]: string } = {
    acquisition: 'Acquisition',
    activation: 'Activation',
    retention: 'Retention',
    referral: 'Referral',
    revenue: 'Revenue'
  };

  return stages.map((stageName, index) => {
    const stage = (metrics.stages as any)[stageName];
    if (!stage) return '';

    const hasGaps = stage.metrics?.some((m: any) =>
      m.gap && !isNegativeGap(m.gap) &&
      (m.gap.rate !== 0 || m.gap.amount !== 0 || m.gap.percentage !== 0)
    );

    return `
      <div class="stage ${hasGaps ? 'has-gaps' : 'on-track'}">
        <div class="stage-header">
          <h2>${stageLabels[stageName]}</h2>
          <p class="stage-goal">${escapeHtml(stage.stage_goal)}</p>
        </div>
        <div class="metrics">
          ${stage.metrics?.map((metric: any) => renderMetric(metric, viability)).join('') || ''}
        </div>
      </div>
      ${index < stages.length - 1 ? '<div class="connector">→</div>' : ''}
    `;
  }).join('');
}

function renderMetric(metric: any, viability: LeanViability | null): string {
  const hasGap = metric.gap && !isNegativeGap(metric.gap);
  const gapClass = hasGap ? 'gap-exists' : 'on-track';

  // Check if target has imported_from
  const hasImport = viability && metric.target?.imported_from;
  const importAnchor = hasImport ? metric.target.imported_from.replace(/\./g, '-') : null;

  return `
    <div class="metric ${gapClass}">
      <div class="metric-name">${escapeHtml(metric.name)}</div>
      ${metric.description ? `<div class="metric-description">${escapeHtml(metric.description)}</div>` : ''}

      <div class="metric-values">
        ${metric.target ? `
          <div class="value-row">
            <span class="label">Target:</span>
            <span class="value ${hasImport ? 'clickable' : ''}" ${hasImport ? `onclick="navigateToViability('${importAnchor}')"` : ''}>
              ${formatMetricValue(metric.target)}
              ${hasImport ? ' <span class="import-icon">↗</span>' : ''}
            </span>
          </div>
          ${hasImport ? `<div class="import-note">From: ${escapeHtml(metric.target.imported_from)}</div>` : ''}
        ` : ''}

        ${metric.current ? `
          <div class="value-row">
            <span class="label">Current:</span>
            <span class="value">${formatMetricValue(metric.current)}</span>
          </div>
        ` : ''}

        ${metric.gap ? `
          <div class="value-row gap-row">
            <span class="label">Gap:</span>
            <span class="gap-value ${hasGap ? 'negative' : 'positive'}">${formatGap(metric.gap)}</span>
          </div>
        ` : ''}
      </div>
    </div>
  `;
}

function formatMetricValue(value: any): string {
  if (value.rate !== undefined && value.period) {
    return `${value.rate}/${value.period}`;
  }
  if (value.amount !== undefined && value.currency) {
    return `${value.currency} ${value.amount.toLocaleString()}`;
  }
  if (value.percentage !== undefined) {
    return `${value.percentage}%`;
  }
  return 'N/A';
}

function renderViabilityContext(viability: LeanViability): string {
  return `
    <div class="viability-context">
      <h2>${escapeHtml(viability.title)}</h2>
      <p class="viability-subtitle">Target sources for AAARR metrics</p>

      <div id="lean-viability-success_criteria-annual_revenue" class="viability-section">
        <h3>Success Criteria</h3>
        <div class="viability-field">
          <span class="field-label">Annual Revenue Target:</span>
          <span class="field-value">${viability.success_criteria.annual_revenue.currency === 'USD' ? '$' : '€'}${viability.success_criteria.annual_revenue.amount.toLocaleString()}</span>
        </div>
      </div>

      ${viability.calculations ? `
        <div class="viability-section">
          <h3>Calculations</h3>
          ${Object.entries(viability.calculations).map(([key, calc]: [string, any]) => `
            <div id="lean-viability-calculations-${key}" class="viability-field">
              <span class="field-label">${key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}:</span>
              <span class="field-value">
                ${calc.rate !== undefined ? `${calc.rate}/${calc.period}` : ''}
                ${calc.amount !== undefined ? `${calc.currency === 'USD' ? '$' : '€'}${calc.amount.toLocaleString()}` : ''}
                ${calc.count !== undefined ? calc.count.toLocaleString() : ''}
                ${calc.percentage !== undefined ? `${calc.percentage}%` : ''}
                ${calc.monthly_rate !== undefined ? `${(calc.monthly_rate * 100).toFixed(2)}%` : ''}
                ${calc.years !== undefined ? `${calc.years} years` : ''}
              </span>
              ${calc.basis || calc.formula ? `<div class="field-note">${escapeHtml(calc.basis || calc.formula)}</div>` : ''}
            </div>
          `).join('')}
        </div>
      ` : ''}

      ${viability.targets ? `
        <div class="viability-section">
          <h3>Targets</h3>
          ${Object.entries(viability.targets).map(([key, target]: [string, any]) => `
            <div id="lean-viability-targets-${key}" class="viability-field">
              <span class="field-label">${key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}:</span>
              <span class="field-value">
                ${Object.entries(target).map(([subKey, value]: [string, any]) => 
                  `${subKey.replace(/_/g, ' ')}: ${value.rate !== undefined ? `${value.rate}/${value.period}` : ''}${value.amount !== undefined ? `${value.currency === 'USD' ? '$' : '€'}${value.amount.toLocaleString()}` : ''}`
                ).join(', ')}
              </span>
            </div>
          `).join('')}
        </div>
      ` : ''}
    </div>
  `;
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

function getStyles(hasTabs: boolean): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }
    .container {
      max-width: 1400px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      padding: 30px;
    }
    header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 2px solid #e0e0e0;
      padding-bottom: 20px;
    }
    h1 { font-size: 2rem; color: #2c3e50; margin-bottom: 10px; }
    .meta { color: #7f8c8d; font-size: 0.9rem; }
    .customer-factory {
      display: flex;
      align-items: stretch;
      gap: 20px;
      margin: 30px 0;
      overflow-x: auto;
      padding: 20px 0;
    }
    .stage {
      flex: 1;
      min-width: 250px;
      border: 2px solid #e0e0e0;
      border-radius: 8px;
      padding: 20px;
      background: #fafafa;
      transition: all 0.3s;
    }
    .stage.has-gaps {
      border-color: #e74c3c;
      background: #fff5f5;
    }
    .stage.on-track {
      border-color: #27ae60;
      background: #f0fff4;
    }
    .stage-header {
      margin-bottom: 20px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 10px;
    }
    .stage-header h2 {
      font-size: 1.3rem;
      color: #2c3e50;
      margin-bottom: 5px;
    }
    .stage-goal {
      font-size: 0.85rem;
      color: #7f8c8d;
      font-style: italic;
    }
    .connector {
      display: flex;
      align-items: center;
      font-size: 2rem;
      color: #95a5a6;
      font-weight: bold;
    }
    .metrics {
      display: flex;
      flex-direction: column;
      gap: 15px;
    }
    .metric {
      background: white;
      border: 1px solid #e0e0e0;
      border-radius: 6px;
      padding: 15px;
    }
    .metric.gap-exists {
      border-left: 4px solid #e74c3c;
    }
    .metric.on-track {
      border-left: 4px solid #27ae60;
    }
    .metric-name {
      font-weight: 600;
      color: #2c3e50;
      margin-bottom: 5px;
    }
    .metric-description {
      font-size: 0.85rem;
      color: #7f8c8d;
      margin-bottom: 10px;
    }
    .metric-values {
      display: flex;
      flex-direction: column;
      gap: 5px;
    }
    .value-row {
      display: flex;
      justify-content: space-between;
      font-size: 0.9rem;
    }
    .label {
      color: #7f8c8d;
      font-weight: 500;
    }
    .value {
      color: #2c3e50;
      font-weight: 600;
    }
    .gap-row {
      margin-top: 5px;
      padding-top: 5px;
      border-top: 1px solid #e0e0e0;
    }
    .gap-value.negative {
      color: #e74c3c;
      font-weight: bold;
    }
    .gap-value.positive {
      color: #27ae60;
      font-weight: bold;
    }
    footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      color: #95a5a6;
      font-size: 0.85rem;
    }
    @media (max-width: 768px) {
      .customer-factory {
        flex-direction: column;
      }
      .connector {
        transform: rotate(90deg);
        margin: 10px 0;
      }
    }
    @media print {
      body { background: white; padding: 0; }
      .container { box-shadow: none; }
      .tabs { display: none; }
      .tab-content { display: block !important; }
    }

    ${hasTabs ? `
    .tabs {
      display: flex;
      gap: 10px;
      margin-bottom: 20px;
      border-bottom: 2px solid #e0e0e0;
    }
    .tab-button {
      padding: 12px 24px;
      background: none;
      border: none;
      border-bottom: 3px solid transparent;
      font-size: 1rem;
      font-weight: 500;
      color: #7f8c8d;
      cursor: pointer;
      transition: all 0.3s;
    }
    .tab-button:hover {
      color: #2c3e50;
      background: #f5f5f5;
    }
    .tab-button.active {
      color: #3498db;
      border-bottom-color: #3498db;
    }
    .tab-content {
      display: none;
    }
    .tab-content.active {
      display: block;
    }
    .clickable {
      cursor: pointer;
      color: #3498db;
      text-decoration: underline;
      transition: all 0.2s;
    }
    .clickable:hover {
      color: #2980b9;
    }
    .import-icon {
      font-size: 0.8em;
      opacity: 0.7;
    }
    .import-note {
      font-size: 0.75rem;
      color: #95a5a6;
      font-style: italic;
      margin-top: 3px;
    }
    .viability-context {
      padding: 20px;
    }
    .viability-subtitle {
      color: #7f8c8d;
      font-size: 0.9rem;
      margin-bottom: 30px;
    }
    .viability-section {
      margin-bottom: 30px;
      padding: 20px;
      background: #f9f9f9;
      border-radius: 8px;
      transition: all 0.3s;
    }
    .viability-section h3 {
      color: #2c3e50;
      margin-bottom: 15px;
      font-size: 1.2rem;
    }
    .viability-field {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e0e0e0;
      transition: all 0.3s;
    }
    .viability-field:last-child {
      border-bottom: none;
    }
    .field-label {
      font-weight: 500;
      color: #7f8c8d;
    }
    .field-value {
      font-weight: 600;
      color: #2c3e50;
    }
    .field-note {
      grid-column: 1 / -1;
      font-size: 0.85rem;
      color: #95a5a6;
      font-style: italic;
      margin-top: 5px;
    }
    .highlight {
      background: #fff3cd !important;
      animation: highlight-fade 2s ease-out;
    }
    @keyframes highlight-fade {
      0% { background: #fff3cd; }
      100% { background: #f9f9f9; }
    }
    ` : ''}
  `;
}
