import { PolicyCharter } from '../parser/types';

export function generatePolicyCharterHTML(policyCharter: PolicyCharter, multiLayer: boolean = false): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(policyCharter.title)} - Policy Charter</title>
    <style>
      ${getStyles()}
      ${multiLayer ? getTreeStyles() : ''}
    </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${escapeHtml(policyCharter.title)}</h1>
      <div class="meta">
        <span>Version: ${escapeHtml(policyCharter.version)}</span>
        <span>Last Updated: ${escapeHtml(policyCharter.last_updated)}</span>
      </div>
    </header>

     ${multiLayer ? `
    <div class="policy-tree">
      <h2>Policy Charter Strategy</h2>
      <div id="policy-tree" class="tree-container"></div>
    </div>
    ` : `
    <div class="tabs">
      <button class="tab active" onclick="switchTab(event, 'goals')">Goals Overview</button>
      <button class="tab" onclick="switchTab(event, 'tactics')">Tactics Tree</button>
      <button class="tab" onclick="switchTab(event, 'policies')">Policies Matrix</button>
      <button class="tab" onclick="switchTab(event, 'risks')">Risk Management</button>
      <button class="tab" onclick="switchTab(event, 'kpis')">KPI Dashboard</button>
    </div>

    <div id="goals" class="tab-content active">
      <h2>Goals Overview</h2>
      ${renderGoalsOverview(policyCharter)}
    </div>

    <div id="tactics" class="tab-content">
      <h2>Tactics Tree</h2>
      ${renderTacticsTree(policyCharter)}
    </div>

    <div id="policies" class="tab-content">
      <h2>Policies Matrix</h2>
      ${renderPoliciesMatrix(policyCharter)}
    </div>

    <div id="risks" class="tab-content">
      <h2>Risk Management</h2>
      ${renderRiskManagement(policyCharter)}
    </div>

    <div id="kpis" class="tab-content">
      <h2>KPI Dashboard</h2>
      ${renderKPIDashboard(policyCharter)}
    </div>
    `}

    <footer>
      <p>Generated by BLUEPRINT - Business Layer Architecture</p>
    </footer>
  </div>

  <script>
    function switchTab(event, tabId) {
      // Hide all tab contents
      document.querySelectorAll('.tab-content').forEach(content => {
        content.classList.remove('active');
      });

      // Remove active from all tabs
      document.querySelectorAll('.tab').forEach(tab => {
        tab.classList.remove('active');
      });

      // Show selected tab content
      document.getElementById(tabId).classList.add('active');

      // Mark selected tab as active
      event.currentTarget.classList.add('active');
    }

    function toggleBracket(button) {
      const content = button.nextElementSibling;
      if (content.style.display === 'none' || content.style.display === '') {
        content.style.display = 'block';
        button.textContent = 'Hide Brackets';
      } else {
        content.style.display = 'none';
        button.textContent = 'Show Brackets';
      }
    }
    </script>

    ${multiLayer ? `
    <script src="https://cdn.jsdelivr.net/npm/d3@7.8.5/dist/d3.min.js"></script>
    <script>
      // Policy tree data
      const treeData = ${JSON.stringify(buildPolicyTree(policyCharter))};

      // Set up SVG dimensions (wider for descriptions)
      const margin = {top: 40, right: 200, bottom: 40, left: 120};
      const width = 1400 - margin.left - margin.right;
      const height = 900 - margin.top - margin.bottom;

      // Set up SVG
      const svg = d3.select('#policy-tree')
        .append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .append('g')
        .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

      // Create tree layout with better spacing
      const treeLayout = d3.tree()
        .size([height, width - 100])  // Leave some margin
        .nodeSize([70, 150]);  // Reasonable node spacing

      // Create root node
      const root = d3.hierarchy(treeData);
      treeLayout(root);

      // Center the tree by adjusting x positions
      const minX = d3.min(root.descendants(), d => d.x) || 0;
      const maxX = d3.max(root.descendants(), d => d.x) || 0;
      const treeWidth = maxX - minX;
      const centerOffset = (width - treeWidth) / 2 - minX;

      // Adjust all node positions to center the tree
      root.each(d => {
        d.x += centerOffset;
      });

      // Add links (arrows)
      svg.selectAll('.link')
        .data(root.links())
        .enter()
        .append('path')
        .attr('class', 'link')
        .attr('d', d3.linkVertical()
          .x(d => d.x)
          .y(d => d.y));

      // Add nodes
      const nodes = svg.selectAll('.node')
        .data(root.descendants())
        .enter()
        .append('g')
        .attr('class', d => \`node \${d.data.type}\`)
        .attr('transform', d => \`translate(\${d.x},\${d.y})\`);

      // Add circles for nodes
      nodes.append('circle')
        .attr('r', 25)
        .attr('fill', d => {
          const colors = {
            'goal': '#FF6B35',
            'tactic': '#4ECDC4',
            'policy': '#45B7D1',
            'risk': '#E74C3C'
          };
          return colors[d.data.type] || '#CCCCCC';
        });

      // Add icons to circles
      nodes.append('text')
        .attr('text-anchor', 'middle')
        .attr('dy', '0.35em')
        .attr('fill', 'white')
        .attr('font-size', '18px')
        .text(d => {
          const icons = {
            'goal': '🎯',
            'tactic': '📝',
            'policy': '☂️',
            'risk': '⛈️'
          };
          return icons[d.data.type] || '●';
        });

      // Add labels
      nodes.append('text')
        .attr('dy', '2.5em')
        .attr('text-anchor', 'middle')
        .attr('fill', '#333')
        .attr('font-size', '12px')
        .style('font-weight', 'bold')
        .text(d => d.data.title);

      // Create tooltip div
      const tooltip = d3.select('#policy-tree')
        .append('div')
        .attr('class', 'policy-tooltip')
        .style('position', 'absolute')
        .style('visibility', 'hidden')
        .style('background', 'rgba(0, 0, 0, 0.8)')
        .style('color', 'white')
        .style('padding', '8px 12px')
        .style('border-radius', '4px')
        .style('font-size', '12px')
        .style('max-width', '300px')
        .style('z-index', '1000')
        .style('pointer-events', 'none');

      // Add mouse events for tooltips
      nodes
        .on('mouseover', function(event, d) {
          const description = d.data.description || 'No description available';
          tooltip
            .style('visibility', 'visible')
            .html('<strong>' + d.data.title + '</strong><br>' + description)
            .style('left', (event.pageX + 10) + 'px')
            .style('top', (event.pageY - 10) + 'px');
        })
        .on('mousemove', function(event) {
          tooltip
            .style('left', (event.pageX + 10) + 'px')
            .style('top', (event.pageY - 10) + 'px');
        })
        .on('mouseout', function() {
          tooltip.style('visibility', 'hidden');
        });
    </script>
    ` : ''}
  </body>
  </html>`;
}

function renderGoalsOverview(policyCharter: PolicyCharter): string {
  if (!policyCharter.goals || policyCharter.goals.length === 0) {
    return '<p>No goals defined</p>';
  }

  return `
    <div class="goals-grid">
      ${policyCharter.goals.map(goal => `
        <div class="goal-card">
          <h3>${escapeHtml(goal.title)}</h3>
          <p class="goal-description">${escapeHtml(goal.description)}</p>
          <div class="goal-meta">
            <div class="meta-item">
              <strong>Addresses:</strong>
              ${goal.addresses && goal.addresses.length > 0
                ? goal.addresses.map(addr => `<span class="tag">${escapeHtml(addr)}</span>`).join('')
                : '<em>None</em>'}
            </div>
            <div class="meta-item">
              <strong>AAARR Impact:</strong>
              ${goal.aaarr_impact && goal.aaarr_impact.length > 0
                ? goal.aaarr_impact.map(stage => `<span class="stage-tag">${escapeHtml(stage)}</span>`).join('')
                : '<em>None</em>'}
            </div>
            <div class="meta-item">
              <strong>Related Tactics:</strong> ${goal.tactics ? goal.tactics.length : 0}
            </div>
            <div class="meta-item">
              <strong>Related Policies:</strong> ${goal.policies ? goal.policies.length : 0}
            </div>
            <div class="meta-item">
              <strong>Related KPIs:</strong> ${goal.kpis ? goal.kpis.length : 0}
            </div>
            <div class="meta-item">
              <strong>Related Risks:</strong> ${goal.risks ? goal.risks.length : 0}
            </div>
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

function renderTacticsTree(policyCharter: PolicyCharter): string {
  if (!policyCharter.tactics || policyCharter.tactics.length === 0) {
    return '<p>No tactics defined</p>';
  }

  return `
    <div class="tactics-tree">
      ${policyCharter.tactics.map(tactic => `
        <div class="tactic-node">
          <div class="tactic-header">
            <h3>${escapeHtml(tactic.title)}</h3>
            <span class="tactic-id">${escapeHtml(tactic.id)}</span>
          </div>
          <p class="tactic-description">${escapeHtml(tactic.description)}</p>
          <div class="tactic-policies">
            <strong>Drives Policies:</strong>
            ${tactic.drives_policies && tactic.drives_policies.length > 0
              ? tactic.drives_policies.map(policyId => {
                  const policy = policyCharter.policies?.find(p => p.id === policyId);
                  return policy ? `<span class="policy-link">${escapeHtml(policy.title)}</span>` : `<span class="missing-policy">${escapeHtml(policyId)}</span>`;
                }).join(', ')
              : '<em>None</em>'}
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

function renderPoliciesMatrix(policyCharter: PolicyCharter): string {
  if (!policyCharter.policies || policyCharter.policies.length === 0) {
    return '<p>No policies defined</p>';
  }

  return `
    <div class="policies-matrix">
      ${policyCharter.policies.map(policy => `
        <div class="policy-card enforcement-${policy.enforcement}">
          <div class="policy-header">
            <h3>${escapeHtml(policy.title)}</h3>
            <span class="enforcement-badge ${policy.enforcement}">${escapeHtml(policy.enforcement)}</span>
          </div>
          <div class="policy-rule">
            <strong>Rule:</strong> ${escapeHtml(policy.rule)}
          </div>
          <div class="policy-tactic">
            <strong>Driven by:</strong>
            ${policy.driven_by_tactic ? (() => {
              const tactic = policyCharter.tactics?.find(t => t.id === policy.driven_by_tactic);
              return tactic ? `<span class="tactic-link">${escapeHtml(tactic.title)}</span>` : `<span class="missing-tactic">${escapeHtml(policy.driven_by_tactic)}</span>`;
            })() : '<em>None</em>'}
          </div>
          ${policy.brackets && policy.brackets.length > 0 ? `
            <div class="policy-brackets">
              <button class="bracket-toggle" onclick="toggleBracket(this)">Show Brackets</button>
              <div class="bracket-content" style="display: none;">
                <h4>Graduated Brackets:</h4>
                ${policy.brackets.map(bracket => `
                  <div class="bracket-item">
                    <div class="bracket-condition"><strong>If:</strong> ${escapeHtml(bracket.condition)}</div>
                    <div class="bracket-rule"><strong>Then:</strong> ${escapeHtml(bracket.rule)}</div>
                  </div>
                `).join('')}
              </div>
            </div>
          ` : ''}
        </div>
      `).join('')}
    </div>
  `;
}

function renderRiskManagement(policyCharter: PolicyCharter): string {
  if (!policyCharter.risks || policyCharter.risks.length === 0) {
    return '<p>No risks defined</p>';
  }

  return `
    <div class="risks-matrix">
      ${policyCharter.risks.map(risk => `
        <div class="risk-card">
          <div class="risk-header">
            <h3>${escapeHtml(risk.description)}</h3>
            <div class="risk-levels">
              <span class="risk-probability probability-${risk.probability}">P: ${escapeHtml(risk.probability)}</span>
              <span class="risk-impact impact-${risk.impact}">I: ${escapeHtml(risk.impact)}</span>
            </div>
          </div>
          <div class="risk-mitigation">
            <strong>Mitigation:</strong>
            ${risk.mitigation && risk.mitigation.length > 0
              ? risk.mitigation.map(mitigationId => {
                  const tactic = policyCharter.tactics?.find(t => t.id === mitigationId);
                  const policy = policyCharter.policies?.find(p => p.id === mitigationId);
                  const item = tactic || policy;
                  return item ? `<span class="mitigation-link">${escapeHtml(item.title)}</span>` : `<span class="missing-mitigation">${escapeHtml(mitigationId)}</span>`;
                }).join(', ')
              : '<em>None</em>'}
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

function renderKPIDashboard(policyCharter: PolicyCharter): string {
  if (!policyCharter.kpis || policyCharter.kpis.length === 0) {
    return '<p>No KPIs defined</p>';
  }

  return `
    <div class="kpis-dashboard">
      ${policyCharter.kpis.map(kpi => `
        <div class="kpi-card">
          <div class="kpi-header">
            <h3>${escapeHtml(kpi.name)}</h3>
            ${kpi.description ? `<p class="kpi-description">${escapeHtml(kpi.description)}</p>` : ''}
          </div>
          <div class="kpi-metrics">
            <div class="kpi-target">
              <strong>Target:</strong> ${formatKPIMetric(kpi.target)}
            </div>
            <div class="kpi-current">
              <strong>Current:</strong> ${formatKPIMetric(kpi.current)}
            </div>
            <div class="kpi-frequency">
              <strong>Frequency:</strong> ${escapeHtml(kpi.measurement_frequency)}
            </div>
          </div>
          <div class="kpi-justification">
            <strong>Justification:</strong> ${escapeHtml(kpi.justification)}
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

function formatKPIMetric(metric: any): string {
  if (metric.rate !== undefined && metric.period) {
    return `${metric.rate}/${metric.period}`;
  }
  if (metric.amount !== undefined && metric.currency) {
    return `${metric.currency} ${metric.amount.toLocaleString()}`;
  }
  if (metric.percentage !== undefined) {
    return `${metric.percentage}%`;
  }
  return 'N/A';
}

function getStyles(): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; padding: 2rem; }
    .container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }

    header { padding: 3rem; border-bottom: 2px solid #e2e8f0; }
    h1 { font-size: 2.5rem; margin-bottom: 0.5rem; color: #1a1a1a; }
    .meta { color: #666; font-size: 0.9rem; }
    .meta span { margin-right: 2rem; }

    .tabs { display: flex; border-bottom: 2px solid #e2e8f0; background: #f9fafb; }
    .tab { padding: 1rem 2rem; cursor: pointer; border: none; background: none; font-size: 1rem; font-weight: 500; color: #4a5568; transition: all 0.2s; }
    .tab:hover { background: #edf2f7; }
    .tab.active { color: #2c5282; border-bottom: 3px solid #4299e1; background: white; }

    .tab-content { display: none; padding: 3rem; }
    .tab-content.active { display: block; }
    .tab-content h2 { font-size: 2rem; margin-bottom: 2rem; color: #1a1a1a; }

    .goals-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 1.5rem; }
    .goal-card { background: white; border: 1px solid #e2e8f0; padding: 1.5rem; border-radius: 6px; transition: transform 0.2s; }
    .goal-card:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
    .goal-card h3 { font-size: 1.25rem; margin-bottom: 0.5rem; color: #1a202c; }
    .goal-description { color: #4a5568; margin-bottom: 1rem; }
    .goal-meta { display: grid; gap: 0.5rem; }
    .meta-item { font-size: 0.9rem; }
    .tag { background: #e2e8f0; color: #4a5568; padding: 0.25rem 0.5rem; border-radius: 3px; margin-right: 0.25rem; font-size: 0.8rem; }
    .stage-tag { background: #4299e1; color: white; padding: 0.25rem 0.5rem; border-radius: 3px; margin-right: 0.25rem; font-size: 0.8rem; }

    .tactics-tree { display: grid; gap: 1.5rem; }
    .tactic-node { background: white; border: 1px solid #e2e8f0; padding: 1.5rem; border-radius: 6px; }
    .tactic-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.5rem; }
    .tactic-header h3 { font-size: 1.25rem; color: #1a202c; }
    .tactic-id { font-size: 0.8rem; color: #666; font-family: monospace; }
    .tactic-description { color: #4a5568; margin-bottom: 1rem; }
    .tactic-policies { font-size: 0.9rem; }

    .policies-matrix { display: grid; gap: 1.5rem; }
    .policy-card { background: white; border: 1px solid #e2e8f0; padding: 1.5rem; border-radius: 6px; }
    .policy-card.enforcement-mandatory { border-left: 4px solid #e53e3e; }
    .policy-card.enforcement-guideline { border-left: 4px solid #3182ce; }
    .policy-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem; }
    .policy-header h3 { font-size: 1.25rem; color: #1a202c; }
    .enforcement-badge { padding: 0.25rem 0.75rem; border-radius: 12px; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; }
    .enforcement-badge.mandatory { background: #fed7d7; color: #c53030; }
    .enforcement-badge.guideline { background: #bee3f8; color: #2c5282; }
    .policy-rule, .policy-tactic { margin-bottom: 0.75rem; font-size: 0.9rem; }
    .bracket-toggle { background: #e2e8f0; border: none; padding: 0.5rem 1rem; border-radius: 4px; cursor: pointer; font-size: 0.9rem; }
    .bracket-content { margin-top: 1rem; padding: 1rem; background: #f9fafb; border-radius: 4px; }
    .bracket-item { margin-bottom: 1rem; padding-bottom: 1rem; border-bottom: 1px solid #e2e8f0; }
    .bracket-item:last-child { border-bottom: none; margin-bottom: 0; }

    .risks-matrix { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 1.5rem; }
    .risk-card { background: white; border: 1px solid #e2e8f0; padding: 1.5rem; border-radius: 6px; }
    .risk-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem; }
    .risk-header h3 { font-size: 1.1rem; color: #1a202c; }
    .risk-levels { display: flex; gap: 0.5rem; }
    .risk-probability, .risk-impact { padding: 0.25rem 0.5rem; border-radius: 3px; font-size: 0.8rem; font-weight: 600; }
    .probability-low { background: #c6f6d5; color: #276749; }
    .probability-medium { background: #fef5e7; color: #744210; }
    .probability-high { background: #fed7d7; color: #c53030; }
    .impact-low { background: #c6f6d5; color: #276749; }
    .impact-medium { background: #fef5e7; color: #744210; }
    .impact-high { background: #fed7d7; color: #c53030; }
    .risk-mitigation { font-size: 0.9rem; }

    .kpis-dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 1.5rem; }
    .kpi-card { background: white; border: 1px solid #e2e8f0; padding: 1.5rem; border-radius: 6px; }
    .kpi-header h3 { font-size: 1.25rem; margin-bottom: 0.5rem; color: #1a202c; }
    .kpi-description { color: #4a5568; margin-bottom: 1rem; }
    .kpi-metrics { display: grid; grid-template-columns: 1fr 1fr; gap: 0.5rem; margin-bottom: 1rem; font-size: 0.9rem; }
    .kpi-frequency { grid-column: span 2; }
    .kpi-justification { font-size: 0.9rem; }

    .policy-link, .tactic-link, .mitigation-link { background: #e2e8f0; color: #4a5568; padding: 0.25rem 0.5rem; border-radius: 3px; margin-right: 0.25rem; font-size: 0.8rem; }
    .missing-policy, .missing-tactic, .missing-mitigation { background: #fed7d7; color: #c53030; padding: 0.25rem 0.5rem; border-radius: 3px; margin-right: 0.25rem; font-size: 0.8rem; }

    footer { padding: 2rem 3rem; border-top: 1px solid #e2e8f0; color: #666; font-size: 0.9rem; text-align: center; }

    @media (max-width: 768px) {
      .container { margin: 0; border-radius: 0; }
      .tabs { flex-direction: column; }
      .tab { padding: 0.75rem 1rem; }
      .goals-grid, .risks-matrix, .kpis-dashboard { grid-template-columns: 1fr; }
      .policy-header { flex-direction: column; gap: 0.5rem; }
      .risk-header { flex-direction: column; gap: 0.5rem; }
      .kpi-metrics { grid-template-columns: 1fr; }
    }
  `;
}

function buildPolicyTree(policyCharter: PolicyCharter) {
  const root: any = {
    title: 'Strategy',
    type: 'root',
    children: []
  };

  policyCharter.goals?.forEach(goal => {
    const goalNode: any = {
      title: goal.title,
      description: goal.description,
      type: 'goal',
      children: []
    };

    goal.tactics?.forEach(tacticId => {
      const tactic = policyCharter.tactics?.find(t => t.id === tacticId);
      if (tactic) {
        const tacticNode: any = {
          title: tactic.title,
          description: tactic.description,
          type: 'tactic',
          children: []
        };

        goal.policies?.forEach(policyId => {
          const policy = policyCharter.policies?.find(p => p.id === policyId);
          if (policy) {
            const policyNode: any = {
              title: policy.title,
              description: policy.rule,
              type: 'policy',
              children: []
            };

            goal.risks?.forEach(riskId => {
              const risk = policyCharter.risks?.find(r => r.id === riskId);
              if (risk) {
                policyNode.children.push({
                  title: risk.description,
                  description: `Probability: ${risk.probability}, Impact: ${risk.impact}`,
                  type: 'risk',
                  children: []
                });
              }
            });

            tacticNode.children.push(policyNode);
          }
        });

        goalNode.children.push(tacticNode);
      }
    });

    root.children.push(goalNode);
  });

  return root;
}

function getTreeStyles(): string {
  return `
    .policy-tree {
      margin: 30px 0;
    }

    .tree-container {
      width: 100%;
      height: 800px;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      background: #fafafa;
      overflow: auto;
    }

    .node {
      cursor: pointer;
    }

    .node circle {
      stroke: #fff;
      stroke-width: 2px;
    }

    .node:hover circle {
      stroke-width: 3px;
    }

    .node text {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      pointer-events: none;
    }

    .link {
      fill: none;
      stroke: #999;
      stroke-width: 2px;
      marker-end: url(#arrowhead);
    }

    .tree-container {
      width: 100%;
      height: 600px;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      overflow: auto;
    }

    .policy-tooltip {
      white-space: normal;
      word-wrap: break-word;
    }

    .node text {
      user-select: none;
    }

    @media print {
      .tree-container {
        display: none;
      }
    }
  `;
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}